
version: 2

models:
  - name: customer_orders
    description: '{{ doc("customer_orders") }}'
    columns: 
      - name: customer_id
        description: "The unique identifier for a customer, sourced from the customers table."
        data_tests:
          - unique 
          - not_null 
      - name: status
        description: "The current processing status of the order. This column is derived and defaults to 'InProgress'."
        data_tests:
          - accepted_values:
              values: ['InProgress']
      - name: customer_id
        description: "The unique identifier for a customer, establishing a relationship with the orders table."
        data_tests:
          - relationships:
              to: source('youtube','orders')
              field: customer_id
      - name: order_id
        description: "The unique identifier for an order, ranging from 0 to 100,000."
        data_tests:
          - range_validation:
              column_name: order_id
              min_value: 0
              max_value: 100000
      - name: order_date
        description: "The date when the order was placed. This value must not be in the future."
        data_tests:
          - no_future_dates:
              column_name: order_date

sources:
  - name: youtube
    database: youtube
    schema: public
    tables:
      - name: restaurants
      - name: menus
      - name: customers
      - name: orders
      - name: orderdetails
      - name: stg_customers
      - name: top_level_email_domains
      - name: sales
